// 6e24bd47e6e60f1424555420c3d8634ca5ae0d23ec381b5968f47f5165422dcb
// Auto-generated by BindingGenerator. Do not edit.
import { call } from "../bridge/runtime";
import type { WryDialogKind, WryDialogButtons } from "./models";

export function Message(message: string, title: string, kind: WryDialogKind, buttons: WryDialogButtons): Promise<string> {
  return call<string>("DialogService.Message", message, title, kind, buttons);
}

export function Ask(message: string, title: string, kind: WryDialogKind): Promise<boolean> {
  return call<boolean>("DialogService.Ask", message, title, kind);
}

export function Confirm(message: string, title: string, kind: WryDialogKind): Promise<boolean> {
  return call<boolean>("DialogService.Confirm", message, title, kind);
}

export function Open(directory: boolean, multiple: boolean, title: string, defaultPath: string, filterName: string, filterExtensions: string): Promise<string[]> {
  return call<string[]>("DialogService.Open", directory, multiple, title, defaultPath, filterName, filterExtensions);
}

export function Save(title: string, defaultPath: string, filterName: string, filterExtensions: string): Promise<string> {
  return call<string>("DialogService.Save", title, defaultPath, filterName, filterExtensions);
}

