// 6e24bd47e6e60f1424555420c3d8634ca5ae0d23ec381b5968f47f5165422dcb
// Auto-generated by BindingGenerator. Do not edit.
import { on, once, off, type EventCallback } from "../bridge/runtime";
import type { ProgressEvent } from "./models";

/**
 * Subscribe to the "progress" event.
 * @returns A dispose function that removes this listener.
 */
export function onProgress(callback: EventCallback<ProgressEvent>): () => void {
  return on<ProgressEvent>("progress", callback);
}

/**
 * Subscribe to the "progress" event for a single occurrence.
 * @returns A dispose function that removes this listener.
 */
export function onceProgress(callback: EventCallback<ProgressEvent>): () => void {
  return once<ProgressEvent>("progress", callback);
}

/**
 * Unsubscribe a callback from the "progress" event.
 */
export function offProgress(callback: EventCallback<ProgressEvent>): void {
  off<ProgressEvent>("progress", callback);
}

