// 6e24bd47e6e60f1424555420c3d8634ca5ae0d23ec381b5968f47f5165422dcb
// Auto-generated by BindingGenerator. Do not edit.
import { call } from "../bridge/runtime";
import type { Person, Employee } from "./models";

export function Greet(name: string): Promise<string> {
  return call<string>("GreetService.Greet", name);
}

export function GetPerson(name: string, age: number): Promise<Person> {
  return call<Person>("GreetService.GetPerson", name, age);
}

export function Add(a: number, b: number): Promise<number> {
  return call<number>("GreetService.Add", a, b);
}

export function GetGreetingAsync(name: string): Promise<string> {
  return call<string>("GreetService.GetGreetingAsync", name);
}

export function GetPeople(): Promise<Person[]> {
  return call<Person[]>("GreetService.GetPeople");
}

export function GetEmployee(name: string, department: string): Promise<Employee> {
  return call<Employee>("GreetService.GetEmployee", name, department);
}

export function EchoBytes(data: string): Promise<string> {
  return call<string>("GreetService.EchoBytes", data);
}

export function GetValueTaskGreeting(name: string): Promise<string> {
  return call<string>("GreetService.GetValueTaskGreeting", name);
}

export function SlowMethod(seconds: number): Promise<string> {
  return call<string>("GreetService.SlowMethod", seconds);
}

export function RunWithProgress(steps: number): Promise<string> {
  return call<string>("GreetService.RunWithProgress", steps);
}

