// 6e24bd47e6e60f1424555420c3d8634ca5ae0d23ec381b5968f47f5165422dcb
// Auto-generated by BindingGenerator. Do not edit.
export * as GreetService from "./GreetService";
export * as DialogService from "./DialogService";
export * from "./models";
export * from "./events";
