// 6e24bd47e6e60f1424555420c3d8634ca5ae0d23ec381b5968f47f5165422dcb
// Auto-generated by BindingGenerator. Do not edit.

export interface Person {
  name: string;
  age: number;
  email?: string;
  display_name: string;
}

export interface Employee extends Person {
  department: string;
  title: string;
}

export enum WryDialogKind {
  Info = 0,
  Warning = 1,
  Error = 2,
}

export enum WryDialogButtons {
  Ok = 0,
  OkCancel = 1,
  YesNo = 2,
  YesNoCancel = 3,
}

export interface ProgressEvent {
  percent: number;
  message: string;
}

