// Auto-generated by BindingGenerator. Do not edit.

export interface Person {
  name: string;
  age: number;
  email?: string;
  display_name: string;
}

export interface Employee extends Person {
  department: string;
  title: string;
}

export interface ProgressEvent {
  percent: number;
  message: string;
}

